server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework: INFO

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EU_USERNAME}:${EU_PASSWORD}@localhost:8761/eureka

  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}