server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:

      httpclient:
        connect-timeout: 5000
        response-timeout: 10s

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      default-filters:
        - AddResponseHeader=X-Gateway, SyncBrand-Gateway
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: lead-service
          uri: lb://lead-service
          predicates:
            - Path=/leads/**

        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/api/organizations/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EU_USERNAME}:${EU_PASSWORD}@localhost:8761/eureka

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO

jwt:
  secret: ${JWT_SECRET}